// Loads songs.json (generated by scripts/build-index.mjs) and handles search + song pages.

const $ = (sel) => document.querySelector(sel);
const listView = $('#list-view');
const songView = $('#song-view');
const input = $('#q');
const results = $('#results');
const count = $('#count');

let songs = [];

// Lowercase, strip accents and apostrophes, turn other punctuation into spaces.
function normalize(s) {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/['’]/g, '')
    .replace(/[^\p{L}\p{N}\s]/gu, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function escapeHtml(s) {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

// Wrap each search word in <mark>, escaping everything else.
function highlight(text, words) {
  if (!words.length) return escapeHtml(text);
  const pattern = new RegExp(`(${words.map((w) => w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|')})`, 'gi');
  return text
    .split(pattern)
    .map((part, i) => (i % 2 ? `<mark>${escapeHtml(part)}</mark>` : escapeHtml(part)))
    .join('');
}

function prepare(song) {
  const lines = song.lyrics.split('\n').filter((l) => l.trim() && !/^\[.*\]$/.test(l.trim()));
  return {
    ...song,
    _title: normalize(song.title),
    _artist: normalize(song.artist),
    _tags: normalize(song.tags.join(' ')),
    _lyrics: normalize(song.lyrics),
    _lines: lines.map((l) => ({ text: l, norm: normalize(l) })),
  };
}

// Every word must appear somewhere; title/artist matches rank above lyric matches.
function search(query) {
  const phrase = normalize(query);
  const words = phrase.split(' ').filter(Boolean);
  if (!words.length) return { words, hits: songs.map((song) => ({ song })) };

  const hits = [];
  for (const song of songs) {
    let score = 0;
    let ok = true;
    for (const w of words) {
      if (song._title.includes(w)) score += 10;
      else if (song._artist.includes(w)) score += 5;
      else if (song._tags.includes(w)) score += 3;
      else if (song._lyrics.includes(w)) score += 1;
      else { ok = false; break; }
    }
    if (!ok) continue;
    if (song._title.includes(phrase)) score += 20;
    if (words.length > 1 && song._lyrics.includes(phrase)) score += 15;

    // Pick the lyric line that best matches, to show as a preview.
    let snippet = null;
    let best = 0;
    for (const line of song._lines) {
      let n = words.filter((w) => line.norm.includes(w)).length;
      if (words.length > 1 && line.norm.includes(phrase)) n += words.length;
      if (n > best) { best = n; snippet = line.text; }
    }
    hits.push({ song, score, snippet });
  }
  hits.sort((a, b) => b.score - a.score || a.song.title.localeCompare(b.song.title));
  return { words, hits };
}

function renderList() {
  const { words, hits } = search(input.value);
  count.textContent = input.value.trim()
    ? `${hits.length} ${hits.length === 1 ? 'match' : 'matches'}`
    : `${songs.length} ${songs.length === 1 ? 'song' : 'songs'}`;

  results.innerHTML = hits
    .map(({ song, snippet }) => `
      <li><a href="#/song/${encodeURIComponent(song.slug)}">
        <span class="title">${highlight(song.title, words)}</span>
        ${song.artist ? `<span class="artist"> · ${highlight(song.artist, words)}</span>` : ''}
        ${snippet ? `<div class="snippet">“${highlight(snippet, words)}”</div>` : ''}
      </a></li>`)
    .join('');
}

function renderSong(slug) {
  const song = songs.find((s) => s.slug === slug);
  if (!song) {
    songView.innerHTML = `<a class="back" href="#/">← All songs</a><p>Song not found.</p>`;
    return;
  }
  const words = normalize(input.value).split(' ').filter(Boolean);
  const meta = [song.artist, song.album, song.year].filter(Boolean).map(escapeHtml).join(' · ');
  const lyrics = song.lyrics
    .split('\n')
    .map((line) => (/^\[.*\]$/.test(line.trim())
      ? `<span class="section">${escapeHtml(line.trim().slice(1, -1))}</span>`
      : highlight(line, words)))
    .join('\n');

  songView.innerHTML = `
    <a class="back" href="#/">← All songs</a>
    <h1>${escapeHtml(song.title)}</h1>
    ${meta ? `<p class="meta">${meta}</p>` : ''}
    ${song.tags.length ? `<ul class="tags">${song.tags.map((t) => `<li>${escapeHtml(t)}</li>`).join('')}</ul>` : ''}
    <div class="lyrics">${lyrics}</div>`;
  document.title = `${song.title} · Lyrics Library`;
}

function route() {
  const match = location.hash.match(/^#\/song\/(.+)$/);
  if (match) {
    listView.hidden = true;
    songView.hidden = false;
    renderSong(decodeURIComponent(match[1]));
    window.scrollTo(0, 0);
  } else {
    songView.hidden = true;
    listView.hidden = false;
    document.title = 'Lyrics Library';
    renderList();
  }
}

input.addEventListener('input', renderList);
window.addEventListener('hashchange', route);

fetch('songs.json')
  .then((r) => {
    if (!r.ok) throw new Error(r.status);
    return r.json();
  })
  .then((data) => {
    songs = data.map(prepare);
    route();
  })
  .catch(() => {
    count.textContent = 'Could not load songs.json — run "node scripts/build-index.mjs" first.';
  });
