// Loads songs.json (generated by scripts/build-index.mjs) and handles the pages of the site:
// the welcome section (#/), the song list with search (#/songs) and song pages (#/song/<slug>).

const $ = (sel) => document.querySelector(sel);
const welcomeView = $('#welcome-view');
const listView = $('#list-view');
const songView = $('#song-view');
const input = $('#q');
const results = $('#results');
const count = $('#count');

let songs = [];
let findSlug = (name) => name; // current file name from an old one, once the songs are loaded

function escapeHtml(s) {
  return s.replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

const { normalize, highlight } = SongSearch;

function renderWelcome() {
  if (songs.length) $('#library-count').textContent = `Search all ${songs.length} songs`;
  const picked = SongSelection.all().length;
  $('#picked-hint').textContent = picked ? `${picked} ${picked === 1 ? 'song' : 'songs'} picked` : '';
}

function renderList() {
  if (!songs.length) {
    count.textContent = 'Loading songs…';
    return;
  }
  const { words, hits } = SongSearch.search(songs, input.value);
  count.textContent = input.value.trim()
    ? `${hits.length} ${hits.length === 1 ? 'match' : 'matches'}`
    : `${songs.length} ${songs.length === 1 ? 'song' : 'songs'} · tap + to pick songs for a song sheet, PowerPoint or subtitles`;

  results.innerHTML = hits
    .map(({ song, snippet }) => `
      <li><a href="#/song/${encodeURIComponent(song.slug)}">
        <span class="title">${highlight(song.title, words)}</span>
        ${song.artist ? `<span class="artist"> · ${highlight(song.artist, words)}</span>` : ''}
        ${snippet ? `<div class="snippet">“${highlight(snippet, words)}”</div>` : ''}
      </a>${SongSelection.pickButton(song.slug, song.title)}</li>`)
    .join('');
}

// Only show the Edit link on devices connected to the admin panel.
function isAdmin() {
  try { return Boolean(localStorage.getItem('lyrics-admin-token')); } catch { return false; }
}

function renderSong(slug) {
  if (!songs.length) {
    songView.innerHTML = ''; // still loading
    return;
  }
  const song = songs.find((s) => s.slug === slug);
  if (!song) {
    songView.innerHTML = `<a class="back" href="#/songs">← All songs</a><p>Song not found.</p>`;
    return;
  }
  const words = normalize(input.value).split(' ').filter(Boolean);
  const meta = [song.artist, song.album, song.year].filter(Boolean).map(escapeHtml).join(' · ');
  const lyrics = song.lyrics
    .split('\n')
    .map((line) => (/^\[.*\]$/.test(line.trim())
      ? `<span class="section">${escapeHtml(line.trim().slice(1, -1))}</span>`
      : highlight(line, words)))
    .join('\n');

  songView.innerHTML = `
    <div class="song-tools">
      <a class="back" href="#/songs">← All songs</a>
      ${isAdmin() ? `<a class="back" href="admin.html#/edit/${encodeURIComponent(song.slug)}">Edit</a>` : ''}
    </div>
    <h1>${escapeHtml(song.title)}</h1>
    <p>${SongSelection.pickButton(song.slug, song.title, true)}</p>
    ${meta ? `<p class="meta">${meta}</p>` : ''}
    ${song.tags.length ? `<ul class="tags">${song.tags.map((t) => `<li>${escapeHtml(t)}</li>`).join('')}</ul>` : ''}
    <div class="lyrics">${lyrics}</div>`;
  document.title = `${song.title} · Lyrics Library`;
}

function route() {
  const match = location.hash.match(/^#\/song\/(.+)$/);
  const view = match ? 'song' : location.hash.startsWith('#/songs') ? 'list' : 'welcome';
  welcomeView.hidden = view !== 'welcome';
  // Highlight "Songs" in the menu on the song list and song pages.
  const songsLink = document.querySelector('.site-nav a[href$="#/songs"]');
  if (view === 'welcome') songsLink.removeAttribute('aria-current');
  else songsLink.setAttribute('aria-current', 'page');
  listView.hidden = view !== 'list';
  songView.hidden = view !== 'song';
  if (view === 'song') {
    // A link with a song's old file name opens the song under its current name.
    const name = decodeURIComponent(match[1]);
    const slug = findSlug(name) || name;
    if (slug !== name) history.replaceState(null, '', `#/song/${encodeURIComponent(slug)}`);
    renderSong(slug);
    window.scrollTo(0, 0);
    return;
  }
  document.title = 'Lyrics Library';
  if (view === 'list') renderList();
  else renderWelcome();
}

input.addEventListener('input', renderList);
SongSelection.mountTray();
SongSelection.onChange(() => { if (!welcomeView.hidden) renderWelcome(); });
window.addEventListener('hashchange', route);
route();

fetch('songs.json', { cache: 'no-cache' })
  .then((r) => {
    if (!r.ok) throw new Error(r.status);
    return r.json();
  })
  .then((data) => {
    songs = data.map(SongSearch.prepare);
    findSlug = SongSearch.slugResolver(data);
    // Songs picked under an old file name follow the song to its new name.
    const picks = SongSelection.all();
    const current = [...new Set(picks.map((slug) => (slug.startsWith('bible:') ? slug : findSlug(slug))).filter(Boolean))];
    if (current.join('\n') !== picks.join('\n')) SongSelection.set(current);
    route();
  })
  .catch(() => {
    count.textContent = 'Could not load songs.json — run "node scripts/build-index.mjs" first.';
  });
